<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Account
 *
 * Generated from protobuf message <code>protocol.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes account_name = 1;</code>
     */
    private $account_name = '';
    /**
     * Generated from protobuf field <code>.protocol.AccountType type = 2;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>bytes address = 3;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>int64 balance = 4;</code>
     */
    private $balance = 0;
    /**
     * Generated from protobuf field <code>repeated .protocol.Account.Vote votes = 5;</code>
     */
    private $votes;
    /**
     * Generated from protobuf field <code>map<string, int64> asset = 6;</code>
     */
    private $asset;
    /**
     * Generated from protobuf field <code>int64 latest_opration_time = 10;</code>
     */
    private $latest_opration_time = 0;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes account_name = 1;</code>
     * @return string
     */
    public function getAccountName()
    {
        return $this->account_name;
    }

    /**
     * Generated from protobuf field <code>bytes account_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountName($var)
    {
        GPBUtil::checkString($var, False);
        $this->account_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.AccountType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.protocol.AccountType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Protocol\AccountType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes address = 3;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 4;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Account.Vote votes = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Account.Vote votes = 5;</code>
     * @param \Protocol\Account_Vote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Account_Vote::class);
        $this->votes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> asset = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAsset()
    {
        return $this->asset;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> asset = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAsset($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT64);
        $this->asset = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 latest_opration_time = 10;</code>
     * @return int|string
     */
    public function getLatestOprationTime()
    {
        return $this->latest_opration_time;
    }

    /**
     * Generated from protobuf field <code>int64 latest_opration_time = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLatestOprationTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->latest_opration_time = $var;

        return $this;
    }

}

