<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\AccountType</code>
 */
class AccountType
{
    /**
     * Generated from protobuf enum <code>Normal = 0;</code>
     */
    const Normal = 0;
    /**
     * Generated from protobuf enum <code>AssetIssue = 1;</code>
     */
    const AssetIssue = 1;
    /**
     * Generated from protobuf enum <code>Contract = 2;</code>
     */
    const Contract = 2;
}

