<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Account.Vote</code>
 */
class Account_Vote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     */
    private $vote_address = '';
    /**
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     */
    private $vote_count = 0;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     * @return string
     */
    public function getVoteAddress()
    {
        return $this->vote_address;
    }

    /**
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVoteAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->vote_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     * @return int|string
     */
    public function getVoteCount()
    {
        return $this->vote_count;
    }

    /**
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoteCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->vote_count = $var;

        return $this;
    }

}

