<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\BlockInventory\Type</code>
 */
class BlockInventory_Type
{
    /**
     * Generated from protobuf enum <code>SYNC = 0;</code>
     */
    const SYNC = 0;
    /**
     * Generated from protobuf enum <code>ADVTISE = 1;</code>
     */
    const ADVTISE = 1;
    /**
     * Generated from protobuf enum <code>FETCH = 2;</code>
     */
    const FETCH = 2;
}

