<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DynamicProperties
 *
 * Generated from protobuf message <code>protocol.DynamicProperties</code>
 */
class DynamicProperties extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 last_solidity_block_num = 1;</code>
     */
    private $last_solidity_block_num = 0;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 last_solidity_block_num = 1;</code>
     * @return int|string
     */
    public function getLastSolidityBlockNum()
    {
        return $this->last_solidity_block_num;
    }

    /**
     * Generated from protobuf field <code>int64 last_solidity_block_num = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastSolidityBlockNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_solidity_block_num = $var;

        return $this;
    }

}

