<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.EmptyMessage</code>
 */
class EmptyMessage extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

}

