<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\Inventory\InventoryType</code>
 */
class Inventory_InventoryType
{
    /**
     * Generated from protobuf enum <code>TRX = 0;</code>
     */
    const TRX = 0;
    /**
     * Generated from protobuf enum <code>BLOCK = 1;</code>
     */
    const BLOCK = 1;
}

