<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\Items\ItemType</code>
 */
class Items_ItemType
{
    /**
     * Generated from protobuf enum <code>ERR = 0;</code>
     */
    const ERR = 0;
    /**
     * Generated from protobuf enum <code>TRX = 1;</code>
     */
    const TRX = 1;
    /**
     * Generated from protobuf enum <code>BLOCK = 2;</code>
     */
    const BLOCK = 2;
    /**
     * Generated from protobuf enum <code>BLOCKHEADER = 3;</code>
     */
    const BLOCKHEADER = 3;
}

