<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\ReasonCode</code>
 */
class ReasonCode
{
    /**
     * Generated from protobuf enum <code>REQUESTED = 0;</code>
     */
    const REQUESTED = 0;
    /**
     * Generated from protobuf enum <code>TCP_ERROR = 1;</code>
     */
    const TCP_ERROR = 1;
    /**
     * Generated from protobuf enum <code>BAD_PROTOCOL = 2;</code>
     */
    const BAD_PROTOCOL = 2;
    /**
     * Generated from protobuf enum <code>USELESS_PEER = 3;</code>
     */
    const USELESS_PEER = 3;
    /**
     * Generated from protobuf enum <code>TOO_MANY_PEERS = 4;</code>
     */
    const TOO_MANY_PEERS = 4;
    /**
     * Generated from protobuf enum <code>DUPLICATE_PEER = 5;</code>
     */
    const DUPLICATE_PEER = 5;
    /**
     * Generated from protobuf enum <code>INCOMPATIBLE_PROTOCOL = 6;</code>
     */
    const INCOMPATIBLE_PROTOCOL = 6;
    /**
     * Generated from protobuf enum <code>NULL_IDENTITY = 7;</code>
     */
    const NULL_IDENTITY = 7;
    /**
     * Generated from protobuf enum <code>PEER_QUITING = 8;</code>
     */
    const PEER_QUITING = 8;
    /**
     * Generated from protobuf enum <code>UNEXPECTED_IDENTITY = 9;</code>
     */
    const UNEXPECTED_IDENTITY = 9;
    /**
     * Generated from protobuf enum <code>LOCAL_IDENTITY = 10;</code>
     */
    const LOCAL_IDENTITY = 10;
    /**
     * Generated from protobuf enum <code>PING_TIMEOUT = 11;</code>
     */
    const PING_TIMEOUT = 11;
    /**
     * Generated from protobuf enum <code>USER_REASON = 12;</code>
     */
    const USER_REASON = 12;
    /**
     * Generated from protobuf enum <code>RESET = 16;</code>
     */
    const RESET = 16;
    /**
     * Generated from protobuf enum <code>UNKNOWN = 255;</code>
     */
    const UNKNOWN = 255;
}

