<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\Transaction\Contract\ContractType</code>
 */
class Transaction_Contract_ContractType
{
    /**
     * Generated from protobuf enum <code>AccountCreateContract = 0;</code>
     */
    const AccountCreateContract = 0;
    /**
     * Generated from protobuf enum <code>TransferContract = 1;</code>
     */
    const TransferContract = 1;
    /**
     * Generated from protobuf enum <code>TransferAssetContract = 2;</code>
     */
    const TransferAssetContract = 2;
    /**
     * Generated from protobuf enum <code>VoteAssetContract = 3;</code>
     */
    const VoteAssetContract = 3;
    /**
     * Generated from protobuf enum <code>VoteWitnessContract = 4;</code>
     */
    const VoteWitnessContract = 4;
    /**
     * Generated from protobuf enum <code>WitnessCreateContract = 5;</code>
     */
    const WitnessCreateContract = 5;
    /**
     * Generated from protobuf enum <code>AssetIssueContract = 6;</code>
     */
    const AssetIssueContract = 6;
    /**
     * Generated from protobuf enum <code>DeployContract = 7;</code>
     */
    const DeployContract = 7;
    /**
     * Generated from protobuf enum <code>WitnessUpdateContract = 8;</code>
     */
    const WitnessUpdateContract = 8;
    /**
     * Generated from protobuf enum <code>ParticipateAssetIssueContract = 9;</code>
     */
    const ParticipateAssetIssueContract = 9;
}

