<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Transaction.raw</code>
 */
class Transaction_raw extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Transaction.TransactionType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int64 ref_block_num = 3;</code>
     */
    private $ref_block_num = 0;
    /**
     * Generated from protobuf field <code>bytes ref_block_hash = 4;</code>
     */
    private $ref_block_hash = '';
    /**
     * Generated from protobuf field <code>int64 expiration = 8;</code>
     */
    private $expiration = 0;
    /**
     * Generated from protobuf field <code>bytes data = 10;</code>
     */
    private $data = '';
    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Contract contract = 11;</code>
     */
    private $contract;
    /**
     * Generated from protobuf field <code>bytes scripts = 12;</code>
     */
    private $scripts = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 14;</code>
     */
    private $timestamp = 0;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.TransactionType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.TransactionType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Protocol\Transaction_TransactionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ref_block_num = 3;</code>
     * @return int|string
     */
    public function getRefBlockNum()
    {
        return $this->ref_block_num;
    }

    /**
     * Generated from protobuf field <code>int64 ref_block_num = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefBlockNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->ref_block_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ref_block_hash = 4;</code>
     * @return string
     */
    public function getRefBlockHash()
    {
        return $this->ref_block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes ref_block_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRefBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->ref_block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 8;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 10;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Contract contract = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContract()
    {
        return $this->contract;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Contract contract = 11;</code>
     * @param \Protocol\Transaction_Contract[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContract($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Transaction_Contract::class);
        $this->contract = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes scripts = 12;</code>
     * @return string
     */
    public function getScripts()
    {
        return $this->scripts;
    }

    /**
     * Generated from protobuf field <code>bytes scripts = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setScripts($var)
    {
        GPBUtil::checkString($var, False);
        $this->scripts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 14;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

