<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     */
    private $raw_data = null;
    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     */
    private $signature;
    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     */
    private $ret;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     * @return \Protocol\Transaction_raw
     */
    public function getRawData()
    {
        return $this->raw_data;
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     * @param \Protocol\Transaction_raw $var
     * @return $this
     */
    public function setRawData($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Transaction_raw::class);
        $this->raw_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignature($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signature = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     * @param \Protocol\Transaction_Result[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Transaction_Result::class);
        $this->ret = $arr;

        return $this;
    }

}

