<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\Transaction\TransactionType</code>
 */
class Transaction_TransactionType
{
    /**
     * Generated from protobuf enum <code>UtxoType = 0;</code>
     */
    const UtxoType = 0;
    /**
     * Generated from protobuf enum <code>ContractType = 1;</code>
     */
    const ContractType = 1;
}

