<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.TXInput.raw</code>
 */
class TXInput_raw extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes txID = 1;</code>
     */
    private $txID = '';
    /**
     * Generated from protobuf field <code>int64 vout = 2;</code>
     */
    private $vout = 0;
    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     */
    private $pubKey = '';

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes txID = 1;</code>
     * @return string
     */
    public function getTxID()
    {
        return $this->txID;
    }

    /**
     * Generated from protobuf field <code>bytes txID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTxID($var)
    {
        GPBUtil::checkString($var, False);
        $this->txID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 vout = 2;</code>
     * @return int|string
     */
    public function getVout()
    {
        return $this->vout;
    }

    /**
     * Generated from protobuf field <code>int64 vout = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVout($var)
    {
        GPBUtil::checkInt64($var);
        $this->vout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     * @return string
     */
    public function getPubKey()
    {
        return $this->pubKey;
    }

    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubKey = $var;

        return $this;
    }

}

