<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.VoteWitnessContract</code>
 */
class VoteWitnessContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    private $owner_address = '';
    /**
     * Generated from protobuf field <code>repeated .protocol.VoteWitnessContract.Vote votes = 2;</code>
     */
    private $votes;
    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     */
    private $support = false;

    public function __construct() {
        \GPBMetadata\Core\Contract::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.VoteWitnessContract.Vote votes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.VoteWitnessContract.Vote votes = 2;</code>
     * @param \Protocol\VoteWitnessContract_Vote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\VoteWitnessContract_Vote::class);
        $this->votes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     * @return bool
     */
    public function getSupport()
    {
        return $this->support;
    }

    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupport($var)
    {
        GPBUtil::checkBool($var);
        $this->support = $var;

        return $this;
    }

}

