<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Witness
 *
 * Generated from protobuf message <code>protocol.Witness</code>
 */
class Witness extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>int64 voteCount = 2;</code>
     */
    private $voteCount = 0;
    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     */
    private $pubKey = '';
    /**
     * Generated from protobuf field <code>string url = 4;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>int64 totalProduced = 5;</code>
     */
    private $totalProduced = 0;
    /**
     * Generated from protobuf field <code>int64 totalMissed = 6;</code>
     */
    private $totalMissed = 0;
    /**
     * Generated from protobuf field <code>int64 latestBlockNum = 7;</code>
     */
    private $latestBlockNum = 0;
    /**
     * Generated from protobuf field <code>int64 latestSlotNum = 8;</code>
     */
    private $latestSlotNum = 0;
    /**
     * Generated from protobuf field <code>bool isJobs = 9;</code>
     */
    private $isJobs = false;

    public function __construct() {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voteCount = 2;</code>
     * @return int|string
     */
    public function getVoteCount()
    {
        return $this->voteCount;
    }

    /**
     * Generated from protobuf field <code>int64 voteCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoteCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->voteCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     * @return string
     */
    public function getPubKey()
    {
        return $this->pubKey;
    }

    /**
     * Generated from protobuf field <code>bytes pubKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPubKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalProduced = 5;</code>
     * @return int|string
     */
    public function getTotalProduced()
    {
        return $this->totalProduced;
    }

    /**
     * Generated from protobuf field <code>int64 totalProduced = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalProduced($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalProduced = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalMissed = 6;</code>
     * @return int|string
     */
    public function getTotalMissed()
    {
        return $this->totalMissed;
    }

    /**
     * Generated from protobuf field <code>int64 totalMissed = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalMissed($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalMissed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 latestBlockNum = 7;</code>
     * @return int|string
     */
    public function getLatestBlockNum()
    {
        return $this->latestBlockNum;
    }

    /**
     * Generated from protobuf field <code>int64 latestBlockNum = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLatestBlockNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->latestBlockNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 latestSlotNum = 8;</code>
     * @return int|string
     */
    public function getLatestSlotNum()
    {
        return $this->latestSlotNum;
    }

    /**
     * Generated from protobuf field <code>int64 latestSlotNum = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLatestSlotNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->latestSlotNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isJobs = 9;</code>
     * @return bool
     */
    public function getIsJobs()
    {
        return $this->isJobs;
    }

    /**
     * Generated from protobuf field <code>bool isJobs = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsJobs($var)
    {
        GPBUtil::checkBool($var);
        $this->isJobs = $var;

        return $this;
    }

}

