<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.WitnessList</code>
 */
class WitnessList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protocol.Witness witnesses = 1;</code>
     */
    private $witnesses;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Witness witnesses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWitnesses()
    {
        return $this->witnesses;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Witness witnesses = 1;</code>
     * @param \Protocol\Witness[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWitnesses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Witness::class);
        $this->witnesses = $arr;

        return $this;
    }

}

