<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/TronInventoryItems.proto

namespace GPBMetadata\Core;

class TronInventoryItems
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a1d636f72652f54726f6e496e76656e746f72794974656d732e70" .
            "726f746f120870726f746f636f6c222d0a0e496e76656e746f7279497465" .
            "6d73120c0a0474797065180120012805120d0a056974656d731802200328" .
            "0c42510a0f6f72672e74726f6e2e70726f746f73421254726f6e496e7665" .
            "6e746f72794974656d735a2a6769746875622e636f6d2f74726f6e70726f" .
            "746f636f6c2f676f2d636c69656e742d6170692f636f7265620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

